# Generated by Django 2.2.19 on 2023-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://www.bonbonentertainment.nl/wp-content/uploads/2021/06/no-image.jpg', max_length=500),
        ),
    ]
