# Generated by Django 2.2.19 on 2023-05-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkm_api', '0004_auto_20230503_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
